// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBitRMADTRZQlxp66lBLctmZ1WqitG23Z8',
    appId: '1:25633711790:web:b7bcaf3a11675438a2af3f',
    messagingSenderId: '25633711790',
    projectId: 'tcpay-93a38',
    authDomain: 'tcpay-93a38.firebaseapp.com',
    storageBucket: 'tcpay-93a38.firebasestorage.app',
    measurementId: 'G-PXQ6XRD0Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkMPG9LwIAD--wiVbxaoX0uGBEDw227PA',
    appId: '1:25633711790:android:72a7872af039ec76a2af3f',
    messagingSenderId: '25633711790',
    projectId: 'tcpay-93a38',
    storageBucket: 'tcpay-93a38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpNriW5CpSmUkCkWcyOdv2ICxyKclbaWA',
    appId: '1:25633711790:ios:4a3b2f9af5b7bd12a2af3f',
    messagingSenderId: '25633711790',
    projectId: 'tcpay-93a38',
    storageBucket: 'tcpay-93a38.firebasestorage.app',
    iosBundleId: 'com.example.flutterImk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpNriW5CpSmUkCkWcyOdv2ICxyKclbaWA',
    appId: '1:25633711790:ios:4a3b2f9af5b7bd12a2af3f',
    messagingSenderId: '25633711790',
    projectId: 'tcpay-93a38',
    storageBucket: 'tcpay-93a38.firebasestorage.app',
    iosBundleId: 'com.example.flutterImk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBitRMADTRZQlxp66lBLctmZ1WqitG23Z8',
    appId: '1:25633711790:web:e6fc5112c9171907a2af3f',
    messagingSenderId: '25633711790',
    projectId: 'tcpay-93a38',
    authDomain: 'tcpay-93a38.firebaseapp.com',
    storageBucket: 'tcpay-93a38.firebasestorage.app',
    measurementId: 'G-NDGNXT3RC0',
  );
}
